using System.Numerics;
using Content.Shared._CM14RTS.Observer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CM14RTS.Observer.UI;

[GenerateTypedNameReferences]
public sealed partial class RTSObserverWarpsWindow : DefaultWindow
{
    private static readonly HashSet<string> Favorites = new();

    private List<RTSObserverWarpPoint> _warps = new();
    private string _searchText = string.Empty;

    public event Action<NetEntity>? OnWarpSelected;

    public RTSObserverWarpsWindow()
    {
        RobustXamlLoader.Load(this);

        SearchBar.OnTextChanged += OnSearchTextChanged;
    }

    public void UpdateWarps(List<RTSObserverWarpPoint> warps)
    {
        _warps = warps;
        Populate();
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text;
        Populate();
        WarpsScroll.SetScrollValue(Vector2.Zero);
    }

    public void Populate()
    {
        FavoritesContainer.DisposeAllChildren();
        AllPointsContainer.DisposeAllChildren();

        var favCount = 0;
        var allCount = 0;

        foreach (var point in _warps)
        {
            var isFav = Favorites.Contains(point.Name);
            var matches = string.IsNullOrWhiteSpace(_searchText) ||
                          point.Name.Contains(_searchText, StringComparison.OrdinalIgnoreCase);

            if (isFav && matches)
            {
                FavoritesContainer.AddChild(CreateWarpRow(point, true));
                favCount++;
            }

            if (matches)
            {
                AllPointsContainer.AddChild(CreateWarpRow(point, isFav));
                allCount++;
            }
        }

        NoFavoritesLabel.Visible = favCount == 0;
        NoPointsLabel.Visible = allCount == 0;
    }

    private BoxContainer CreateWarpRow(RTSObserverWarpPoint point, bool isFavorite)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 1),
        };

        var starButton = new Button
        {
            Text = isFavorite ? "★" : "☆",
            MinSize = new Vector2(34, 26),
            ToolTip = Loc.GetString(isFavorite ? "rts-observer-warps-unstar" : "rts-observer-warps-star"),
            Margin = new Thickness(0, 0, 4, 0),
            ModulateSelfOverride = isFavorite ? Color.FromHex("#ffd700") : null,
        };

        starButton.OnPressed += _ =>
        {
            if (Favorites.Contains(point.Name))
                Favorites.Remove(point.Name);
            else
                Favorites.Add(point.Name);

            Populate();
        };

        var warpButton = new Button
        {
            Text = point.Name,
            TextAlign = Label.AlignMode.Left,
            HorizontalExpand = true,
            ClipText = true,
            MinSize = new Vector2(260, 26),
            ToolTip = Loc.GetString("rts-observer-warps-teleport-tooltip", ("name", point.Name)),
        };

        warpButton.OnPressed += _ =>
        {
            OnWarpSelected?.Invoke(point.Entity);
        };

        row.AddChild(starButton);
        row.AddChild(warpButton);
        return row;
    }
}
